# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4567f3d535cd78b3a3c722e6f7820abc6e1f29bc72450884e7c4973bae97129f1a4c7a4926fc30c6b70e185b6d0954f41e801e25f57d853b956dc2dabd05bba8

test:
  secret_key_base: ffd53a9a50e373019938cb69d0b08ea0044cdc3f03f4462a24a8aa837da4e51d4ccd466473b8ba125305a0f745dc29832629ba284242a4e30bbe7f8bc3ad5caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
